spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url:
    username:
    password:

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
        format_sql: true
        show_sql: true
  sql:
    init:
      mode: always
      