CREATE TABLE IF NOT EXISTS users
(
    user_id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_email VARCHAR(64) NOT NULL,
    user_name  VARCHAR(32) NOT NULL,
    UNIQUE (user_email, user_name)
);

CREATE TABLE IF NOT EXISTS chats
(
    chat_id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    chat_title      VARCHAR(100) NOT NULL UNIQUE,
    chat_created_on TIMESTAMP WITHOUT TIME ZONE
);

CREATE TABLE IF NOT EXISTS users_chats
(
    user_id BIGINT REFERENCES users (user_id) ON DELETE CASCADE,
    chat_id BIGINT REFERENCES chats (chat_id) ON DELETE CASCADE,
    UNIQUE (user_id, chat_id)
);


CREATE TABLE IF NOT EXISTS message
(
    message_id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    message_text       VARCHAR(500) NOT NULL,
    message_user_id    BIGINT REFERENCES users (user_id) ON DELETE CASCADE,
    message_chat_id    BIGINT REFERENCES chats (chat_id) ON DELETE CASCADE,
    message_created_on TIMESTAMP WITHOUT TIME ZONE
);